language: java

jdk:
  - oraclejdk8

sudo: required

before_install:
 - chmod +x gradlew
 
before_script:
 - mkdir lib/
 - wget -P "lib/" https://github.com/Max-Tkachenko/java-libraries/junit-4.10.jar

script:
  - ./gradlew clean build -i --continue
