language: java

jdk:
  - oraclejdk8

sudo: required

before_install:
 - chmod +x gradlew
 - wget -O https://github.com/Max-Tkachenko/java-libraries/junit-4.10.jar

script:
  - ./gradlew clean build -i --continue
