language: java

jdk:
  - oraclejdk8

sudo: required

before_install:
 - chmod +x gradlew
 
script:
  - ./gradlew clean build -i --continue
  
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
